"use client";

import { Activity, ArrowUpRight, ChevronDown, Clock3, GitBranch, Mail, MoreHorizontal, Plus, Sparkles, Users, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { cn } from "@walls/utils";

const panelGlassClass = "bg-white/80 backdrop-blur-xl shadow-[0_8px_28px_rgba(15,23,42,0.07),inset_0_1px_0_rgba(255,255,255,0.95)]";
const numberFormatter = new Intl.NumberFormat("en-US");

type DashboardData = {
  range: { start: string; end: string; days: number };
  metrics: { revenue: string | null; activeProfiles: number; emailsDelivered: number; conversion: number | null; totalOccurrences: number; totalRuns: number };
  daily: Array<{ date: string; count: number }>;
  flows: Array<{ id: string; name: string; trigger: string; status: string; profiles: number; conversion: number | null; revenue: string | null }>;
};

export function FlowsDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showFlowPreview, setShowFlowPreview] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/dashboard").then(async (response) => {
      const payload = (await response.json().catch(() => ({}))) as DashboardData & { error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Unable to load dashboard");
      if (!cancelled) setData(payload);
    }).catch((loadError) => {
      if (!cancelled) setError(loadError instanceof Error ? loadError.message : "Unable to load dashboard");
    });
    return () => { cancelled = true; };
  }, []);

  const maxDailyCount = useMemo(() => Math.max(...(data?.daily.map((item) => item.count) ?? [0]), 1), [data]);
  const rangeLabel = data ? `${formatDate(data.range.start)} – ${formatDate(data.range.end)}` : "Last 30 days";

  return <div className="min-h-full bg-kenoo-white">
    <div className="mx-auto max-w-[1440px] px-6 py-8 sm:px-10 lg:px-12">
      <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-[12px] font-medium uppercase tracking-[0.1em] text-[#9b9b9b]">Customer engagement</p><h1 className="text-[30px] font-semibold tracking-[-0.04em] text-[#111]">Make every customer moment count.</h1><p className="mt-2 max-w-[560px] text-[14px] leading-6 text-[#777]">Build intelligent email journeys that respond to what your customers do next.</p></div><button onClick={() => setShowFlowPreview(true)} className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#111] px-4 py-2.5 text-[13px] font-medium text-white shadow-sm transition hover:bg-[#2a2a2a]"><Plus className="h-4 w-4" /> Create flow</button></div>
      {error ? <div className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[12px] text-red-700">{error}</div> : null}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Attributed revenue" value={data?.metrics.revenue ?? "—"} icon={Activity} /><MetricCard label="Active profiles" value={data ? numberFormatter.format(data.metrics.activeProfiles) : "—"} icon={Users} /><MetricCard label="Emails delivered" value={data ? numberFormatter.format(data.metrics.emailsDelivered) : "—"} icon={Mail} /><MetricCard label="Run conversion" value={formatPercent(data?.metrics.conversion)} icon={ArrowUpRight} /></section>
      <section className="mt-8 grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className={cn("rounded-[28px] p-5 sm:p-6", panelGlassClass)}><div className="mb-5 flex items-start justify-between"><div><h2 className="text-[15px] font-semibold tracking-[-0.02em]">Event activity</h2><p className="mt-1 text-[12px] text-[#909090]">Events received by Flows over the selected period</p></div><span className="flex items-center gap-1.5 rounded-md border border-[#e7e7e7] px-2.5 py-1.5 text-[11px] text-[#737373]">{rangeLabel} <ChevronDown className="h-3 w-3" /></span></div><div className="flex h-[190px] items-end gap-2 border-b border-[#eeeeee] px-2 pb-0 pt-5 sm:gap-3">{(data?.daily ?? []).map((item) => <div key={item.date} className="group flex h-full flex-1 items-end"><div className="relative w-full rounded-t-md bg-[#d9f2e6] transition-all group-hover:bg-[#b9e8d0]" style={{ height: `${Math.max((item.count / maxDailyCount) * 100, item.count ? 4 : 0)}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-[#111] px-1.5 py-1 text-[9px] text-white group-hover:block">{numberFormatter.format(item.count)} events</span></div></div>)}</div><div className="flex justify-between px-1 pt-3 text-[10px] text-[#aaa]"><span>{data ? formatDate(data.range.start) : "—"}</span><span>{data ? formatDate(addDays(data.range.start, 7)) : "—"}</span><span>{data ? formatDate(addDays(data.range.start, 14)) : "—"}</span><span>{data ? formatDate(addDays(data.range.start, 21)) : "—"}</span><span>{data ? formatDate(data.range.end) : "—"}</span></div></div><div className="rounded-[28px] bg-[#111] p-6 text-white shadow-[0_8px_28px_rgba(15,23,42,0.07)]"><div className="mb-8 flex items-center justify-between"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#2b2b2b]"><Sparkles className="h-4 w-4 text-[#c7f3dc]" /></div><span className="rounded-full bg-[#214e38] px-2 py-1 text-[10px] font-medium text-[#baf0d1]">Live snapshot</span></div><h2 className="text-[18px] font-medium leading-7 tracking-[-0.02em]">{snapshotTitle(data)}</h2><p className="mt-3 text-[12px] leading-5 text-[#a8a8a8]">{snapshotDescription(data)}</p></div></section>
      <section className={cn("mt-8 rounded-[28px]", panelGlassClass)}><div className="flex flex-col justify-between gap-4 border-b border-[#eeeeee] px-5 py-5 sm:flex-row sm:items-center sm:px-6"><div><h2 className="text-[15px] font-semibold tracking-[-0.02em]">Your flows</h2><p className="mt-1 text-[12px] text-[#909090]">Automations that react to customer behavior</p></div><button onClick={() => setShowFlowPreview(true)} className="flex w-fit items-center gap-2 rounded-lg border border-[#e5e5e5] px-3 py-2 text-[12px] font-medium text-[#555] hover:bg-[#f8f8f8]"><Plus className="h-3.5 w-3.5" /> New flow</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-[#f1f1f1] text-[10px] uppercase tracking-[0.1em] text-[#a0a0a0]"><th className="px-6 py-3 font-medium">Flow</th><th className="px-4 py-3 font-medium">Trigger</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Profiles</th><th className="px-4 py-3 text-right font-medium">Conversion</th><th className="px-4 py-3 text-right font-medium">Revenue</th><th className="w-10 px-4 py-3" /></tr></thead><tbody>{data?.flows.map((flow) => <tr key={flow.id} className="group border-b border-[#f3f3f3] last:border-0 hover:bg-[#fcfcfc]"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f1f8f4] text-[#238252]"><GitBranch className="h-3.5 w-3.5" /></div><span className="text-[13px] font-medium text-[#222]">{flow.name}</span></div></td><td className="px-4 py-4 text-[12px] text-[#777]"><span className="inline-flex items-center gap-1.5"><Zap className="h-3 w-3 text-[#b18522]" />{flow.trigger}</span></td><td className="px-4 py-4"><StatusBadge status={flow.status} /></td><td className="px-4 py-4 text-right text-[12px] text-[#555]">{numberFormatter.format(flow.profiles)}</td><td className="px-4 py-4 text-right text-[12px] text-[#555]">{formatPercent(flow.conversion)}</td><td className="px-4 py-4 text-right text-[12px] font-medium text-[#222]">{flow.revenue ?? "—"}</td><td className="px-4 py-4 text-right"><button className="rounded-md p-1.5 text-[#aaa] opacity-0 transition hover:bg-[#f0f0f0] hover:text-[#444] group-hover:opacity-100"><MoreHorizontal className="h-4 w-4" /></button></td></tr>)}</tbody></table>{data && data.flows.length === 0 ? <p className="px-6 py-12 text-center text-[12px] text-[#999]">No flows have been saved yet.</p> : null}</div></section>
    </div>
    {showFlowPreview && <div className="fixed inset-0 z-20 flex items-center justify-center bg-black/20 p-4" onClick={() => setShowFlowPreview(false)}><div className="w-full max-w-[620px] rounded-2xl border border-[#e5e5e5] bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-[11px] font-medium uppercase tracking-[0.1em] text-[#9a9a9a]">Create a flow</p><h2 className="mt-1 text-[22px] font-semibold tracking-[-0.03em]">Start with a customer moment.</h2><p className="mt-2 text-[13px] text-[#777]">Choose a trigger and Flows will help you build the next best action.</p></div><button onClick={() => setShowFlowPreview(false)} className="text-2xl leading-none text-[#aaa]">×</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><TriggerCard icon={Clock3} title="Abandoned checkout" description="Customer starts checkout but does not purchase" /><TriggerCard icon={Users} title="New profile added" description="A new person enters your audience" /><TriggerCard icon={Mail} title="Email engagement" description="A person opens or clicks a message" /><TriggerCard icon={Zap} title="Custom event" description="React to an event from your apps or API" /></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setShowFlowPreview(false)} className="rounded-lg px-3 py-2 text-[12px] text-[#777] hover:bg-[#f7f7f7]">Cancel</button><button onClick={() => setShowFlowPreview(false)} className="rounded-lg bg-[#111] px-4 py-2 text-[12px] font-medium text-white">Continue</button></div></div></div>}
  </div>;
}

function MetricCard({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { return <div className={cn("rounded-[28px] p-5", panelGlassClass)}><div className="flex items-start justify-between"><p className="text-[12px] text-[#858585]">{label}</p><Icon className="h-4 w-4 text-[#a0a0a0]" /></div><div className="mt-5"><p className="text-[24px] font-semibold tracking-[-0.04em]">{value}</p></div></div>; }
function StatusBadge({ status }: { status: string }) { const color = status === "active" ? "bg-[#dff7eb] text-[#14804a]" : status === "paused" ? "bg-[#fff4d6] text-[#9a6800]" : status === "archived" ? "bg-[#f3f3f3] text-[#737373]" : "bg-[#eef3ff] text-[#536ea8]"; return <span className={`rounded-full px-2 py-1 text-[10px] font-medium ${color}`}>{status[0]?.toUpperCase()}{status.slice(1)}</span>; }
function TriggerCard({ icon: Icon, title, description }: { icon: typeof Clock3; title: string; description: string }) { return <button className="group rounded-xl border border-[#e7e7e7] p-4 text-left transition hover:border-[#b7dcca] hover:bg-[#f8fcfa]"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#eef8f2] text-[#238252] transition group-hover:bg-[#dff3e8]"><Icon className="h-4 w-4" /></div><p className="mt-3 text-[13px] font-medium">{title}</p><p className="mt-1 text-[11px] leading-4 text-[#858585]">{description}</p></button>; }
function formatPercent(value: number | null | undefined) { return value == null ? "—" : `${value.toFixed(1)}%`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(value)); }
function addDays(value: string, days: number) { const date = new Date(value); date.setDate(date.getDate() + days); return date.toISOString(); }
function snapshotTitle(data: DashboardData | null) { if (!data) return "Loading your live activity."; if (!data.metrics.totalOccurrences && !data.metrics.totalRuns) return "Your account is ready for its first event."; if (data.metrics.totalRuns) return `${numberFormatter.format(data.metrics.totalRuns)} workflow ${data.metrics.totalRuns === 1 ? "run is" : "runs are"} being tracked.`; return `${numberFormatter.format(data.metrics.totalOccurrences)} events received in the last 30 days.`; }
function snapshotDescription(data: DashboardData | null) { if (!data) return "Fetching the latest event, audience, and workflow data."; if (!data.metrics.totalOccurrences && !data.metrics.totalRuns) return "Send an event through your configured API key to start building an audience and measuring flow activity."; return `${numberFormatter.format(data.metrics.activeProfiles)} profiles are currently in your Flow audience, with ${numberFormatter.format(data.metrics.emailsDelivered)} completed email steps recorded in this period.`; }
